name: Run Example Demo Tests
on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]
jobs:
    api-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              working-directory: ./examples/advanced/tests
              run: npm install

            - name: Test Advanced Examples
              working-directory: ./examples/advanced/tests
              run: npx mocha --no-timeouts advanced_test.js

            - name: Test Basic Examples
              working-directory: ./examples/tests
              run: npx mocha --no-timeouts basic_examples.js
